// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdV-QJREOjUw32Ue83WW6B_WmRTdfuWKU',
    appId: '1:739804141924:web:eb4111ee28fc30e7fe0271',
    messagingSenderId: '739804141924',
    projectId: 'bucket-list-d4f3d',
    authDomain: 'bucket-list-d4f3d.firebaseapp.com',
    databaseURL: 'https://bucket-list-d4f3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bucket-list-d4f3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrkKBnt7U_4sUc5a8ey2vgaca8mSpUn8k',
    appId: '1:739804141924:android:a7854c5834e037ddfe0271',
    messagingSenderId: '739804141924',
    projectId: 'bucket-list-d4f3d',
    databaseURL: 'https://bucket-list-d4f3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bucket-list-d4f3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5uM5mmMN4XGXt0O6aQnyW1E5I3EO1-Jk',
    appId: '1:739804141924:ios:f0cc8df3d18c54fffe0271',
    messagingSenderId: '739804141924',
    projectId: 'bucket-list-d4f3d',
    databaseURL: 'https://bucket-list-d4f3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bucket-list-d4f3d.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5uM5mmMN4XGXt0O6aQnyW1E5I3EO1-Jk',
    appId: '1:739804141924:ios:f0cc8df3d18c54fffe0271',
    messagingSenderId: '739804141924',
    projectId: 'bucket-list-d4f3d',
    databaseURL: 'https://bucket-list-d4f3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bucket-list-d4f3d.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdV-QJREOjUw32Ue83WW6B_WmRTdfuWKU',
    appId: '1:739804141924:web:e41b53bbcae67d92fe0271',
    messagingSenderId: '739804141924',
    projectId: 'bucket-list-d4f3d',
    authDomain: 'bucket-list-d4f3d.firebaseapp.com',
    databaseURL: 'https://bucket-list-d4f3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bucket-list-d4f3d.firebasestorage.app',
  );

}